### ISSUE TITLE
request for contribution

### ISSUE THREAD

**Issue by BachAmadou** [MQuaresma/Universal-Time-and-Date-Calculator#2]
Hi, im Bachir i would like to contribute to this project. please more information is needed. thanks

**Comment by MQuaresma** [comment]
Hey Bachir, this is a project for academic purposes only, as such there's very little contribution that can be made in an open source context. Feel free to fork it and play around with it if you want though! :)

**Comment by BachAmadou** [comment]
Hi, ok I see, thanks a lot.
